language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - commitlint-travis

before_deploy:
  - yarn build

deploy:
  skip_cleanup: true
  provider: npm
  email: $EMAIL
  api_key:
    secure: $API_KEY
  on:
    tags: true
    repo: iclouds/wordpress-sdk
